### ISSUE TITLE
Possible bug with Inner() option

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/ImageFiltering.jl#116]
Consider the following example:

```julia
using GeoStatsImages
using ImageFiltering
using Plots

# load an example 100x100 image
img = training_image("Strebelle")[1:100,1:100,1]

# trivial smoothing kernel
kern = ones(30,30)

# works as expected
res = imfilter(img, centered(kern), Algorithm.FFT())
heatmap(res)
```
![Screenshot from 2019-11-07 21-24-22](https://user-images.githubusercontent.com/3345261/68439352-0d721280-01a6-11ea-85bd-7a567a7e20ea.png)

```julia
# now with the Inner() option
res = imfilter(img, centered(kern), Inner(), Algorithm.FFT())
heatmap(res)
```
![Screenshot from 2019-11-07 21-26-04](https://user-images.githubusercontent.com/3345261/68439407-3a262a00-01a6-11ea-82b5-a78b762f960a.png)

There is some strange offset. Could you please confirm the bug?

**Comment by johnnychen94** [comment]
For FFT algorithm, `kern` will be shifted and padded to of the same size of `img`. Looks like the shifting and padding part doesn't work properly.

**Comment by juliohm** [comment]
It may also be a simpler bug like indexing the final result incorrectly to
produce the inner part of the full image. If the result without inner is a
OffsetArray for example doing `res[30:100-30,30:100-30]` may be
innapropriate.

**Comment by juliohm** [comment]
Appreciate if someone familiar with the code can take a look at this. ImageFiltering.jl is one of the few packages that I can't contribute straightforwardly, the code is advanced and full of indirect dispatch calls. Tried falling the calls with the debugger, but it still very challenging to find the point where the indexing is going wrong.

**Comment by timholy** [comment]
Test `master`. No release yet because we need to figure out the upper bounding of all of JuliaImages, and I haven't had time to do that yet.

**Comment by juliohm** [comment]
Tests fail for me on master:

![Screenshot from 2019-11-09 15-12-11](https://user-images.githubusercontent.com/3345261/68533226-5809a100-0304-11ea-9f5a-c67b60fe5b13.png)

However, the issue reported above does not happen.

**Comment by timholy** [comment]
Weird, it's passing on Travis: https://travis-ci.org/JuliaImages/ImageFiltering.jl?utm_medium=notification&utm_source=github_status
