### ISSUE TITLE
Feature request: Moffat kernel

### ISSUE THREAD

**Issue by gerrygralton** [JuliaImages/ImageFiltering.jl#146]
If anyone gets a chance, the implementation of a kernel using the Moffat distribution would be extremely useful.
Cheers!

**Comment by timholy** [comment]
If you want to give it a whirl yourself, try adding it to `src/kernels.jl` (plus a test in `test/specialty.jl`). A likely model to follow is [LoG](https://github.com/JuliaImages/ImageFiltering.jl/blob/46c0445e239974791ebe6033ba77bf809d65a9fc/src/kernel.jl#L254-L278).
