### ISSUE TITLE
Reorganize the documentation

### ISSUE THREAD

**Issue by timholy** [JuliaImages/ImageFiltering.jl#153]
This package has some lovely, but long, documentation strings. Starting with Julia 1.5, the REPL will let you choose between brief and extended help. The documentation of this package should be reorganized to take advantage of that structure. PR #151 illustrates what this process might look like.

**Comment by johnnychen94** [comment]
I've proposed a documentation guide months ago based on the style used by @zygmuntszpak 
 when I was new to Julia https://github.com/JuliaImages/Images.jl/issues/790 Perhaps it's the time to review it?

**Comment by Kunz-David** [comment]
Hello,
I was wondering if there is way of viewing the documentation for this package in a HTML version. (Perhaps something exported with Documenter.jl that can be added to the Images.jl package documentation? Or is there a way to generate the docs for this package localy? - here I don't know how I would go about it though.)
I would be fantastic to have some webpage where I can read the docstrings of functions from this package with functional Latex.  The Latex parts of the docstrings in Juno aren't human-readable.

I apologise if this isn't the right place to request it or ask for help, I think of a better way.

**Comment by timholy** [comment]
https://juliaimages.org/stable/, specifically https://juliaimages.org/stable/imagefiltering/ and the API reference in https://juliaimages.org/stable/function_reference/#Image-algorithms-1.

**Comment by Kunz-David** [comment]
> https://juliaimages.org/stable/, specifically https://juliaimages.org/stable/imagefiltering/ and the API reference in https://juliaimages.org/stable/function_reference/#Image-algorithms-1.
> 
> EDIT: if you forget where it is, when searching it's the top hit for "JuliaImages"

Thanks for the help. I was looking for the API. Turns out I was just blind :(
