### ISSUE TITLE
does not handle integer ...why???

### ISSUE THREAD

**Issue by postoroniy** [JuliaImages/ImageFiltering.jl#17]
I have data in integer and integer kernel.
after run imfilter on such data got this
ERROR: InexactError()
 in unsafe_setindex! at /home/slava/.julia/v0.5/OffsetArrays/src/OffsetArrays.jl:153 [inlined]
 in __imfilter_inbounds!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::CartesianRange{CartesianIndex{2}}, ::Float64) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:532
 in _imfilter_inbounds!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::Tuple{UnitRange{Int64},UnitRange{Int64}}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:499
 in imfilter!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::Tuple{UnitRange{Int64},UnitRange{Int64}}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:483
 in _imfilter_tiled!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Int16,2,Array{Int16,2}}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::Array{Array{Float64,2},1}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:346
 in imfilter!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Int16,2,Array{Int16,2}}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:278
 in imfilter!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::Array{Int16,2}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.Pad{0}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:220
 in imfilter!(::Array{Int16,2}, ::Array{Int16,2}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.Pad{0}, ::ImageFiltering.Algorithm.FIRTiled{2}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:143
 in imfilter(::Array{Int16,2}, ::OffsetArrays.OffsetArray{Int16,2,Array{Int16,2}}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:5

if I convert integer array data into float then it's ok - no error.

**Comment by timholy** [comment]
Can you give a more complete example? Like this:
```julia
julia> img = rand(UInt8, 20)
20-element Array{UInt8,1}:
 0x3b
 0xca
 0x18
 0xcb
 0xfa
 0xa2
 0x82
 0x58
 0xd9
 0x15
 0xee
 0x7f
 0x01
 0x7d
 0x57
 0xbd
 0xf3
 0xa5
 0x12
 0x4a

julia> kernel = rand(Int8, 3)
3-element Array{Int8,1}:
   -9
   42
 -119

julia> imfilter(img, centered(kernel))
20-element Array{Int64,1}:
 -22091
   5097
 -24967
 -21440
 -10605
 -10916
  -6470
 -23297
   5823
 -29393
  -5306
   3073
 -15976
  -5112
 -19962
 -21762
 -11130
   2601
  -9535
  -5860
```

**Comment by postoroniy** [comment]
try this
```
imfilter(rand(Int16,128,128),Int16[1 2 2 2 1])
```
ERROR: InexactError()
 in unsafe_setindex! at /home/slava/.julia/v0.5/OffsetArrays/src/OffsetArrays.jl:153 [inlined]
 in __imfilter_inbounds!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::CartesianRange{CartesianIndex{2}}, ::Float64) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:532
 in _imfilter_inbounds!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::Tuple{UnitRange{Int64},UnitRange{Int64}}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:499
 in imfilter!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::Tuple{UnitRange{Int64},UnitRange{Int64}}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:483
 in _imfilter_tiled!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Int16,2,Array{Int16,2}}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::Array{Array{Float64,2},1}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:346
 in imfilter!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::OffsetArrays.OffsetArray{Int16,2,Array{Int16,2}}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.NoPad{ImageFiltering.Pad{0}}, ::Tuple{Base.OneTo{Int64},Base.OneTo{Int64}}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:278
 in imfilter!(::ComputationalResources.CPU1{ImageFiltering.Algorithm.FIRTiled{2}}, ::Array{Int16,2}, ::Array{Int16,2}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.Pad{0}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:220
 in imfilter!(::Array{Int16,2}, ::Array{Int16,2}, ::Tuple{OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}},OffsetArrays.OffsetArray{Float64,2,Array{Float64,2}}}, ::ImageFiltering.Pad{0}, ::ImageFiltering.Algorithm.FIRTiled{2}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:143
 in imfilter(::Array{Int16,2}, ::Array{Int16,2}) at /home/slava/.julia/v0.5/ImageFiltering/src/imfilter.jl:5

**Comment by postoroniy** [comment]
does not matter Int16 or UInt16, same error

**Comment by timholy** [comment]
Your filtered values are overflowing (in other words, getting an error is great, although the message explaining the problem could be nicer). Try to explicitly specify the output type, `imfilter(Float32, rand(Int16,128,128), Int16[1 2 2 2 1])`.

**Comment by postoroniy** [comment]
how is the final range of filtered data assumed?
if it's supposed to be the same as input then yes, it's ok.
but I expected to get result without care of that range and in fact I am aware of overflowing range of 16 bits, 
therefore, isn't it better to return result in float32 or 64 or int64 with some warning?

**Comment by timholy** [comment]
Logic is [here](https://github.com/JuliaImages/ImageFiltering.jl/blob/0bbf1a3d059955ff0f5c87afce77f858c9ffd2a6/src/imfilter.jl#L974-L980), it basically uses the same rules as multiplication and addition of numbers in Julia. But hmm, it might be better to `widen` the type, i.e., return `Int32` when both inputs are `Int16`.

**Comment by postoroniy** [comment]
automatically widening  is important for me  when developing algorithm rather than being focused "todo _right_ things":-)

**Comment by timholy** [comment]
Within limits. Everyone hated it when `::UInt8 * ::UInt8` gave `UInt64`. But for something that might accumulate a lot of values, it makes sense.

**Comment by postoroniy** [comment]
it makes sense  return uint16 when uint8 * uint8, and etc.
and when one of them float - > return float64( 32???)

**Comment by timholy** [comment]
Like i said, Julia used those rules initially, but in practice almost everyone hated it. There has been much less complaining since it was changed to have behavior more in line with other "serious" computational languages.

**Comment by postoroniy** [comment]
ok... I see.
I guess it's  worth to fork and use my own branch for myself
thanks

**Comment by timholy** [comment]
No, you don't understand. I'm fixing this now here. What I'm saying is that multiplication of scalars follows C-like rules, but for filtering I agree it's worth changing the standard rules.

**Comment by postoroniy** [comment]
but then
"There has been much less complaining since it was changed to have behavior more in line with other "serious" computational languages."
doesn't break this by your changes/fixes :-D?

**Comment by timholy** [comment]
No. We already have different rules for accumulation, and filtering is a form of accumulation. Observe:
```julia
julia> 0xff + 0xff
0xfe

julia> sum([0xff, 0xff])
0x000001fe
```
As weird as it may seem, it's been much more popular this way than it was back when `0xff+0xff` gave a `UInt`.

**Comment by timholy** [comment]
Hmm, now that I've been living with this change a little longer, I am less of a fan. The problems are:
- it's inconsistent with other "filtering" behavior in base julia (e.g., `cumsum`, `.+`)
- it risks quadrupling the storage requirements. For people who work with big images, that's a problem. 
- I really don't like the fact that `imfilter([1,2,3], [1])` was returning an `Int128` array.

So there's a do-over in #22.
