### ISSUE TITLE
Improve imfilter docstring

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/ImageFiltering.jl#184]
The `imfilter` docstring is an amazing learning resource, but I think it is not addressing the goal of a docstring. In my opinion, the docstring should clarify the usage of the function and explain the options quickly via examples. Currently, however, it explains what is a filtering operation, differences between correlation and convolution, and a lot of related theoretical results, which aren't very useful. This information is appropriate for the official docs, but are not appropriate in the docstring. Additionally, the docstring contains LaTeX code which is not properly displayed in the REPL.

**Comment by timholy** [comment]
#151, #153

**Comment by timholy** [comment]
Just waiting for a volunteer!
