### ISSUE TITLE
resolve_window method ambiguity

### ISSUE THREAD

**Issue by JeffFessler** [JuliaImages/ImageFiltering.jl#208]
I just learned about Aqua.jl and decided to try it on some of my favorite packages like this one.
It reported exactly one method ambiguity here:

`resolve_window(window::Tuple{Vararg{Int64,N}} where N) in ImageFiltering.MapWindow at /Users/fessler/.julia/dev/ImageFiltering/src/mapwindow.jl:122`

`resolve_window(window::Tuple{Vararg{AbstractUnitRange,N}} where N) in ImageFiltering.MapWindow at /Users/fessler/.julia/dev/ImageFiltering/src/mapwindow.jl:134`

The only ambiguity is for the empty Tuple `()` so I've added a 1-line fix to #207.

**Comment by johnnychen94** [comment]
Seems to be fixed by #207 already.
