### ISSUE TITLE
Fix Documenter build

### ISSUE THREAD

**Issue by feanor12** [JuliaImages/ImageFiltering.jl#220]
I see two options at the moment:
1.)  Change the Documenter compat value of DemoCards.jl
2.) Change the compat value of the docs folder to include 0.26
eg.  `Documenter = "0.26, 0.27"`

**Comment by johnnychen94** [comment]
Oh sorry, it was a rush, I'll upgrade DemoCards to be compatible with Documenter v0.27 tomorrow~

**Comment by johnnychen94** [comment]
With DemoCards v0.4.3 out, it works now.
