### ISSUE TITLE
Incorrect usage of `threadid`

### ISSUE THREAD

**Issue by cafaxo** [JuliaImages/ImageFiltering.jl#265]
This usage of `threadid` definitely does not look correct:
https://github.com/JuliaImages/ImageFiltering.jl/blob/afd33f4e2903bc29f37cfe38afc2b7d7ff1142d8/src/imfilter.jl#L487-L493
See https://julialang.org/blog/2023/07/PSA-dont-use-threadid/#the_buggy_pattern

**Comment by mkitti** [comment]
This probably should at least use the static scheduler if not be refactored.

**Comment by IanButterworth** [comment]
I would refactor it. Using the static scheduler isn't a great stopgap re. composability
