### ISSUE TITLE
Add stride argument for mapwindow

### ISSUE THREAD

**Issue by jw3126** [JuliaImages/ImageFiltering.jl#44]
Sometimes, I need to apply a function to a window, which slides over an image. Just like what `mapwindow` does, except that I want my window to move by bigger steps. Would it be an option to add an additional argument to `mapwindow` that allows to select how far the window moves in each dimension? For example in the case of `Matrix` it behaves as follows:
```julia 
mapwindow(f, args...; stride=(3,2)) == mapwindow(f, args..., windowsize)[1:3:end,1:2:end]
```
except that the unnecessary computations are omitted. If there is interest in this I can implement it.

**Comment by timholy** [comment]
I think it's a great idea. The one extra thing that I think needs consideration is how to specify an offset, to achieve the same thing as
```julia
mapwindow(f, args...)[2:3:end,2:2:end]
```
or maybe even
```julia
mapwindow(f, args...)[101:3:128, 40:3,77]
```
to focus on an ROI.
 
We could use both `stride` and `offset` keywords, but I wonder if a better approach would be founded on passing the ranges themselves so that you can specify an extra endpoint.

**Comment by jw3126** [comment]
Yeah full control over the ranges sounds good. And lots of narrow keyword arguments are a mixed blessing. My only problem is, that I am mostly interested in the stride case  and this is awkward to express as ranges.
But I guess this could be solved with a helper function `strided(indices(img), (2,3))`.

**Comment by jw3126** [comment]
If I want to iterate over a product of unit ranges, I can to `CartesianRange(some_unitranges)`. What is a good way to iterate over a product of non unit ranges?

**Comment by timholy** [comment]
There's `Iterators.product`

**Comment by jw3126** [comment]
Closing  #45.
