### ISSUE TITLE
Add Gabor filters

### ISSUE THREAD

**Issue by yakir12** [JuliaImages/ImageFiltering.jl#50]
[Gabor filters](https://en.wikipedia.org/wiki/Gabor_filter) are very useful to have 😃

**Comment by arijitkar98** [comment]
@yakir12 @timholy Hey, I am new to JuliaImages. If no one is working on it, I would like to start contributing by implementing this.

**Comment by zygmuntszpak** [comment]
This issue can be closed due to the merge of #57.
