### ISSUE TITLE
WARNING: Method definition _bcs1(Any, Any)

### ISSUE THREAD

**Issue by juliohm** [JuliaImages/ImageFiltering.jl#90]
This warning is known?

```julia
WARNING: Method definition _bcs1(Any, Any) in module Broadcast at broadcast.jl:439 overwritten in module ImageFiltering at /home/juliohm/.julia/packages/ImageFiltering/qNVTb/src/ImageFiltering.jl:23
```

**Comment by timholy** [comment]
#89. Will be fixed by Julia 1.0.4 and/or Julia 1.1.0.

**Comment by dlfivefifty** [comment]
This is still present in Julia v1.0.5: https://travis-ci.org/JuliaHolomorphic/ComplexPhasePortrait.jl/jobs/624582224

**Comment by timholy** [comment]
It will always give that warning on 1.0.x: https://github.com/JuliaLang/julia/pull/30164#issuecomment-525351282
