### ISSUE TITLE
mapwindow custom anchor

### ISSUE THREAD

**Issue by jc211** [JuliaImages/ImageFiltering.jl#91]
mapwindow is a very nice utility. I wonder if it would be possible to also change the anchor. At the moment only odd sized windows are allowed. Perhaps by allowing the anchor to be changed to the corner, even sized windows can be allowed as well.

**Comment by jw3126** [comment]
It is already possible to choose the anchor wherever you want:
```julia
img = 1:10
window = (0:3,)
mapwindow(maximum, img, window)
```

**Comment by timholy** [comment]
If there's some improvement that's needed in the docs, please point out where.
