### ISSUE TITLE
Bug in 3d cascade

### ISSUE THREAD

**Issue by timholy** [JuliaImages/ImageFiltering.jl#92]
From https://discourse.julialang.org/t/best-approach-to-smooth-array-none-of-my-approaches-are-very-useful/17633/12?u=tim.holy (with some typos fixed):

```julia
using ImageFiltering, Test

a = rand(10,10,10);
b = similar(a);
kf2 = kernelfactors((ones(3)/3, ones(3)/3))
kf3 =  kernelfactors((ones(3)/3, ones(3)/3, [1.0]))
for i in 1:10
       b[:,:,i] = imfilter(a[:,:,i], kf2)
end
c = imfilter(a, kf3);
b == c
```
gives `false`. And it's not just floating-point roundoff: the only slice they agree on is `c[:,:,10]`.

**Comment by aramirezreyes** [comment]
Interesting. Thanks for taking a look.
