### ISSUE TITLE
Lazy padarray?

### ISSUE THREAD

**Issue by jw3126** [JuliaImages/ImageFiltering.jl#98]
I think it would be useful to have a lazy variant of `padarray`. E.g. a thin wrapper around the array that computes border values in `getindex` calls. 
I have the feeling that this thing exists already somewhere? If not, is there interest of having that functionality here?

**Comment by timholy** [comment]
There's [PaddedViews](https://github.com/JuliaArrays/PaddedViews.jl). But it's not as flexible. Yes, it probably makes sense to do that.

**Comment by jw3126** [comment]
Solved by #99
